import esbuild from "esbuild";

const production = process.argv.includes("production");

const context = await esbuild.context({
  entryPoints: ["packages/ante-obsidian-plugin/src/obsidian/main.ts"],
  bundle: true,
  format: "cjs",
  platform: "node",
  target: "es2021",
  sourcemap: production ? false : "inline",
  minify: production,
  treeShaking: true,
  outfile: "main.js",
  external: ["obsidian", "electron"],
  banner: {
    js: "/* Generated by esbuild */"
  }
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
